name: Main

on: [push]

jobs:
  run-ci:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        FOLDER: [gatsby-starter, nextjs-sdk, nextjs-starter, pcc, vue-sdk]

    name: Run Type Check & Linters
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'yarn'

      - name: Install dependencies of root
        run: yarn install --frozen-lockfile

      - name: Install dependencies of subfolder
        run: yarn install --frozen-lockfile
        working-directory: ${{ matrix.FOLDER }}

      # - name: Check linting
      #   run: yarn lint

      - name: Build package
        run: yarn build
        working-directory: ${{ matrix.FOLDER }}
